nome = str(input('Digite o seu nome completo: ')).strip().split()
print(nome)
print (' Muito prazer  ')
print (' Seu primeiro nome é: {}'.format(nome[0]) )
print (' Seu Ultimo nome é: {}'.format(nome [len(nome) - 1]))
