print('***** Parque das compras ***** ')
prod = input ('Digite o nome do produto: ')
valor = float(input('Digite o valor do produto: R$'))
desconto = valor - (valor * 10/100)
parce1 = valor + (valor * 5/100)
parce2 = valor + (valor * 6/100)
parce3 = valor + (valor * 8/100)

print('\n O nome do produto é: {} '.format(prod))
print('O pagamento à vista {:.2f} com desconto de 10% \n'.format(desconto))
print('Os pagamentos no cartão terá um acrescimo')
print('Pagamento parcelado em 1 vez: R$ {:.2f}'.format(parce1))
print('Pagamento parcelado em 2 vezes: R$ {:.2f}'.format(parce2))
print('Pagamento parcelado em 3 vezes: R$ {:.2f}'.format(parce3))
